# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daily Programmer | c13u
email: d.chege711@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My attempts at solving challenges posted in /r/dailyprogrammer.
baseurl: "" # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.c13u.com/reddit_daily_programmer" 
# twitter_username: Chege
github_username:  dchege711
github: [metadata]

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
exclude: [Easy, Hard, Intermediate, Scripts, Timeless_Discussions, Bonus]
permalink: /:categories/:year/:month/:day/:title:output_ext
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  easy_challenges:
    output: true
  intermediate_challenges:
    output: true
  hard_challenges:
    output: true
  380_smooshed_morse_code:
    output: true

collections_dir: challenges
